### ISSUE TITLE
Expected release date?

### ISSUE THREAD

**Issue by lorenmt** [arnold-benchmark/arnold#1]
Hi Arnold team,

Really excited about this new robotics dataset. Wondering what's the expected release date? I have a control framework which might be suitable for this benchmark and would love to test it out soon.

Cheers,

**Comment by huangjy-pku** [comment]
Thanks for your attention. We are currently refining code details for some tasks for more coherent structures. The code will be expected to release within 1~2 weeks :)

**Comment by lorenmt** [comment]
That would be great! Just wondering whether you could provide the object names/types for grasping instructions as well, if that would be convient? Just to love to see the variations?

**Comment by huangjy-pku** [comment]
The object names/types are determined by the target object. For example, it will be "the bottle" if the target is a bottle. The variations this part provides are limited. Instead, the variations mainly come from the descriptions of goal states and compositionalities of phrases.

**Comment by huangjy-pku** [comment]
The release finally comes. Really sorry for such a delay.
