### ISSUE TITLE
arnold requirments 

### ISSUE THREAD

**Issue by abdotaarek** [arnold-benchmark/arnold#10]
can i use arnold conda-based on a GTX gpu laptop? can i make isaac sim from omniverse works without ray tracing

**Comment by nikepupu** [comment]
Unfortunately, right now, only RTX GPUs are supported.

**Comment by abdotaarek** [comment]
thanks

**Comment by abdotaarek** [comment]
I have another question, so is it a must to use Rtx to run arnold because the environment or i can use another model that works in gtx

**Comment by nikepupu** [comment]
Isaac sim environment only supports RTX GPUs.

**Comment by abdotaarek** [comment]
Sorry for too many questions but can i run it on ubuntu 22.04 and nividia driver 535.54.03
