### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by abdotaarek** [arnold-benchmark/arnold#13]
hello, when im trying to train using this line ´python train_peract.py task=pickup_object model=peract lang_encoder=clip mode=train batch_size=8 steps=100000´ it gives me this error:

File "/media/local/atarek/miniconda3/envs/arnold/lib/python3.7/random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

"how should i exactly modify the  default.yaml file"

**Comment by huangjy-pku** [comment]
Can you provide a complete error log? Seems you are sampling from an empty sequence. I wonder at which line it occurs.
