### ISSUE TITLE
nvidia-driver-525.60.11 has security vulnerabilities

### ISSUE THREAD

**Issue by teason30** [arnold-benchmark/arnold#14]
NVIDIA driver version 525.60.11 is quite old and has security vulnerabilities.  Can other versions of the 525 driver be used?  It looks as though anything prior to 525.125.06 is vulnerable.

https://nvidia.custhelp.com/app/answers/detail/a_id/5468

**Comment by atharva7am** [comment]
Any updates on this? I'm working on a headless server where 525.60.11 shall not be installed due to vulnerability issues.
Docker support for the latest drivers is much requested. @nikepupu @huangjy-pku

**Comment by nikepupu** [comment]
Maybe you can try to play with the Dockerfile? Community support is much appreciated for this issues at the moment. I apologize for this.  I am not really an expert on isaac sim - nvidia driver compatability issues.  I actually tried a bunch of versions. The one I mentioned is the only driver version I found to be functional around the time of release along with the docker file.

**Comment by nikepupu** [comment]
I can confirm 535.113.01 also works.
