### ISSUE TITLE
editing ground truth actions

### ISSUE THREAD

**Issue by abdotaarek** [arnold-benchmark/arnold#18]

**Comment by abdotaarek** [comment]
hello, is it possible to change the ground truth actions

**Comment by huangjy-pku** [comment]
Of course, you can assign `gt_actions` in `eval.py` on your own.

**Comment by abdotaarek** [comment]
Also, one more question, how can i evaluate only one episode that i choose from the demonstration npz files.

**Comment by huangjy-pku** [comment]
Your code is ok, I think. To evaluate on a specific demonstration, you can add some operations in `load_data` function. For example:
```python
for npz_path in demo_path:
    if file_name not in npz_path:   # add
        continue   # add
    data.append(np.load(npz_path, allow_pickle=True))
    frames.append(npz_path)
```

**Comment by abdotaarek** [comment]
Thank you, appreciate the fast response.

**Comment by abdotaarek** [comment]
Hi, i gave the peract model the customized gt as you said in the eval script, i gave it the position, orientation, and the gripper state.
But the task failed, should the Gt actions be more than these 3 informations?

**Comment by nikepupu** [comment]
How do you provide position, orientation, and the gripper state? Peract does not have 100 % success rate . Please refer to the paper.

**Comment by huangjy-pku** [comment]
Why would you overwrite the gt actions? We have provided them in the demonstration file. If you want to overwrite, make sure the customized action is accurate.
