### ISSUE TITLE
Any ETA for making the benchmark dataset available?

### ISSUE THREAD

**Issue by Jack-XHP** [arnold-benchmark/arnold#2]
Hi this is an exciting and impressive work for a photo-realistic robot task demonstration dataset.  I would like to try it out for my project, any ETA for releasing the dataset or the rendering code base?

**Comment by nikepupu** [comment]
Hi Jack,
Thanks for your interest in our project. The code refactoring is taking longer than expected. We will be providing a docker image when we release everything, as the setup process is non-trivial. We will let you know when everything is ready.

**Comment by chanhee-luke** [comment]
Hi @nikepupu. Is there any update on the progress? This dataset looks to be very exciting and I'm looking forward to using it!

**Comment by huangjy-pku** [comment]
The release finally comes. Really sorry for such a delay.
