### ISSUE TITLE
No module named 'carb'

### ISSUE THREAD

**Issue by xiaohao9999** [arnold-benchmark/arnold#22]
Hi,

When I complete the training and run the ckpt_selection file, the following error occurs:

```
Traceback (most recent call last):
  File "eval.py", line 19, in <module>
    from environment.runner_utils import get_simulation
  File "/data1/ws/arnold/environment/runner_utils.py", line 4, in <module>
    import carb
ModuleNotFoundError: No module named 'carb'
```

Can you guide me on how to do it?

**Comment by xiaohao9999** [comment]
It can only be evaluate based on docker installation, right?

**Comment by nikepupu** [comment]
Hi, Carb is a module used by nvidia isaac sim. Did you have isaac sim installed?

**Comment by xiaohao9999** [comment]
Hi,

I noticed https://github.com/arnold-benchmark/arnold/issues/14#issuecomment-1955647785. Can you install isaac sim 2022.1.1 under the 535.113.01?

My server driver version is 530.41.03, But I always can’t install  isaac sim 2022.1.1. Error occurred:
```
/data/.loacl/share/ov/pkg/isaac_sim-2022.1.1/omni.isaac.sim.post.install.sh: line 17: 41841 Segmentation fault      (core dumped) ${SCRIPT_DIR}/omni.isaac.sim.warmup.sh
```
Can you guide me on how to do it?

**Comment by nikepupu** [comment]
On my Ubuntu 20.04, with driver version 535.113.01. The installation works. I can install it from the launcher.

**Comment by nikepupu** [comment]
maybe refer to here: https://github.com/arnold-benchmark/arnold/issues/20

**Comment by xiaohao9999** [comment]
Sorry to bother you again. When I execute `ckpt_selection, some errors occur:

![image](https://github.com/arnold-benchmark/arnold/assets/146507142/da6d6e05-281d-4808-9850-f6e5082f7503)

**Comment by nikepupu** [comment]
It seems that assets are not placed in the correct location.
