### ISSUE TITLE
Can't find eval_challenge_dev.sh & eval_challenge.sh

### ISSUE THREAD

**Issue by SanMumumu** [arnold-benchmark/arnold#25]
Hi, 

`cd /root/arnold/`
`bash eval_challenge_dev.sh ${checkpoint_file} # for dev phase`
`bash eval_challenge.sh ${checkpoint_file} # for test phase`

I notice these in document, but I can't find these two files. Could you tell me where can I download them?

**Comment by huangjy-pku** [comment]
Make sure you are cloning the `challenge` branch by `git clone -b challenge https://github.com/arnold-benchmark/arnold.git`

**Comment by nikepupu** [comment]
In addition, if you have outdated cache when building docker, please pull the latest content from github

**Comment by SanMumumu** [comment]
Thank you very much for your prompt reply.
