### ISSUE TITLE
Can't find hand.dae .

### ISSUE THREAD

**Issue by nightsky-nostar** [arnold-benchmark/arnold#26]
I notice that in inference.ipynb, you have a file named "hand.dae"

`gripper_trimesh = trimesh.load('/mnt/huangjiangyong/VRKitchen/hand.dae', force='mesh')`

Could you tell me how to get this file?

**Comment by huangjy-pku** [comment]
This file is borrowed from [PerAct](https://github.com/peract/peract). I forget where I got this file. Send me an email [edgeoberjy@gmail.com](mailto:edgeoberjy@gmail.com) and I will reply with this file.
