### ISSUE TITLE
Python 3.8 does not support eval.

### ISSUE THREAD

**Issue by xiaohao9999** [arnold-benchmark/arnold#27]
Hi,

When I use the python3.8 environment, an error will be reported when eval：

![image](https://github.com/arnold-benchmark/arnold/assets/146507142/f7299852-2a68-40f8-a143-1119f8d9e65e)

Does Isaac sim2022.1.1 only support python3.7 version? But I have some libraries that require python>=3.8, what should I do?

**Comment by nikepupu** [comment]
Unfortunately, Isaac sim2022.1.1 only supports python3.7.

**Comment by xiaohao9999** [comment]
Well, is it okay if I use the latest Isaac sim 2023.1.1?

**Comment by nikepupu** [comment]
Unfortunately, you will need to update all the camera-related utilities.

**Comment by xiaohao9999** [comment]
That's too bad, but thanks for your timely reply.
