### ISSUE TITLE
Problems with the results of the experiment

### ISSUE THREAD

**Issue by ljy1234-special** [arnold-benchmark/arnold#28]
Hello!As you can see in the picture below, I'd like to ask you about your article where the results are accurate to two decimal places and more precise, but after executing the eval.py file I only get results like 0.10 or 0.15, etc. that `end in 0 and 5`. What is the reason for this?
![图片1](https://github.com/arnold-benchmark/arnold/assets/114971643/6b284466-56eb-4da1-ac79-1a1e33878199)

**Comment by nikepupu** [comment]
Hi 
Thanks for your interest in our work. 
If you are interested in getting more decimal places, feel free to modify this line of code:
 https://github.com/arnold-benchmark/arnold/blob/main/eval.py#L224

**Comment by ljy1234-special** [comment]
> Hi Thanks for your interest in our work. If you are interested in getting more decimal places, feel free to modify this line of code: https://github.com/arnold-benchmark/arnold/blob/main/eval.py#L224

Thank you for your timely reply!But I would also like to ask what is the variable `total` in line 224 of the code? 20 or some other number?
![image](https://github.com/arnold-benchmark/arnold/assets/114971643/f5ae4209-a6d7-40f3-9f8c-ed7972ddb622)

**Comment by huangjy-pku** [comment]
`total` is the number of evaluated data. For normal evaluation, it is the size of the corresponding eval split. For challenge-oriented evaluation, this number is much smaller.

**Comment by ljy1234-special** [comment]
I got you. Thank you so much!I hope you'll produce more exciting results in the future！
