### ISSUE TITLE
Issues for submission of final results

### ISSUE THREAD

**Issue by ljy1234-special** [arnold-benchmark/arnold#29]
Hello. I'm sorry to bother you again. I have submitted the baseline after entering the submit command 'evalai challenge 2266 phase 4501 submit --file submission_test.zip --large ---public' in conda environment. But the baseline I tested locally is not 0. What is the reason for this?
![a3636e00022e62ac176a61875b4b0b7](https://github.com/arnold-benchmark/arnold/assets/114971643/99c063e2-c0e4-4206-98d6-f47074c49bfb)

**Comment by nikepupu** [comment]
Which split did you run? Did you run the dev split but submit to the test split?

**Comment by nikepupu** [comment]
please make sure to use the challenge branch.

**Comment by ljy1234-special** [comment]
I'm sure we ran and submitted the test split.The three steps are as follows:
![image](https://github.com/arnold-benchmark/arnold/assets/114971643/3c139152-45eb-468e-aff4-024cdc07d138)
![image](https://github.com/arnold-benchmark/arnold/assets/114971643/1b098ab9-69a9-4317-8066-2d376330ba8f)
![image](https://github.com/arnold-benchmark/arnold/assets/114971643/215d5087-23b0-4aa1-a2de-f990e4a067eb)

Also, we do use main branch for` training` and `evaluation`. So, is it feasible to use `the results of main brach training` for testing in `challenge branch`? Or do we have to retrain in `challenge branch`?

**Comment by nikepupu** [comment]
You don't have to retrain. Can you send me an email with the submission ID?

**Comment by ljy1234-special** [comment]
Okay, I'm sending it.

**Comment by nikepupu** [comment]
I found something very interesting: the file name will differ when using non-English operating systems. I am working on a fix now.

**Comment by nikepupu** [comment]
It's now fixed. I have rerun the submission; you should be able to see the updated results. 

Thank you for bringing this up!
