### ISSUE TITLE
Questions about camera extrinsics

### ISSUE THREAD

**Issue by SanMumumu** [arnold-benchmark/arnold#31]
Hi,

I noticed that the values ​​of the rotation matrix and translation matrix of the camera extrinsic are too different, and is the translation matrix in centimeters? Is the rotation matrix also in centimeters?

![image](https://github.com/arnold-benchmark/arnold/assets/88917267/7cbeaff3-d7c6-4144-8aa3-abea10191c25)

**Comment by huangjy-pku** [comment]
The translation is in centimeters here while the rotation concerns some `sin` and `cos` values.

**Comment by SanMumumu** [comment]
Sorry to bother you again, 
This `pose` matrix  is ​​the inverse matrix of the camera’s extrinsics matrix, right?
I want to use this `pose ` matrix to help me achieve volume rendering. But it seems that the light generated by `pose ` does not pass through the picture. Like below. Do you know how to solve this problem? 
Thank you very much！

![image](https://github.com/arnold-benchmark/arnold/assets/88917267/6c9df9b1-5aeb-4daf-b322-2db8e19d8682)

**Comment by huangjy-pku** [comment]
@nikepupu

**Comment by nikepupu** [comment]
to extract translation and rotation please refer to https://github.com/arnold-benchmark/arnold/blob/40ad6861f45b676bf538b7a0e180d81c8d454823/utils/transforms.py#L145

**Comment by SanMumumu** [comment]
OK, thanks a lot!
