### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by ishikasingh** [arnold-benchmark/arnold#34]
I am trying to save rendered videos during eval as following while recording:
```
self.recorder.record_data(
                robot_states=dof_states,
                actions=actions,
                time_step=self.time_step,
                frame=self.render()
            )
```
but the eval is getting really slow - taking >10min per episode. Is there a way to make it faster?

**Comment by nikepupu** [comment]
Hi,

You can modify the render() function. There is a bug with isaac sim skip frame rendering, so we render multiple times and put a sleep() there. You can delete the sleep and only render once if you are trying to record every frame.

**Comment by ishikasingh** [comment]
Okay thanks, is this not the right way to record, because I don't see anything happening for peract model's successful episodes either?

**Comment by nikepupu** [comment]
Can you try visualize the output for self.render()?

**Comment by ishikasingh** [comment]
It works, there was a bug on my end in copying the frame to the buffer list, thanks for your quick response!
