### ISSUE TITLE
Error from vagrant during setup

### ISSUE THREAD

**Issue by Reagan1311** [arnold-benchmark/arnold#4]
Thanks for the awesome work! I got the following error when runing the "vagrant up". I was wondering do I need to modify something in the Vagrantfile? Thanks in advance.

> Bringing machine 'default' up with 'virtualbox' provider...
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> vm:
> \* A box must be specified.

**Comment by nikepupu** [comment]
Hi, 

Can you provide more information?
Do you have Docker installed? 
and did you compile the Docker image?

**Comment by Reagan1311** [comment]
Sorry, this was fixed when enabling the root user. Thanks!
