### ISSUE TITLE
Problem in visualization

### ISSUE THREAD

**Issue by charlottejruby** [arnold-benchmark/arnold#41]
Thanks for your awesome work!

I am running Arnold using Docker. However, the Pick and Place task in Isaac Sim runs successfully within the Docker container, but the visualization does not work.

I think the visualization is not working due to the error shown below. Could you please help me resolve this issue? I would greatly appreciate it.

![Screenshot from 2024-09-06 20-27-03](https://github.com/user-attachments/assets/650f7d1f-4e0b-4dfd-8cf5-b9f1b1a8295c)

**Comment by nikepupu** [comment]
Did you disable headless mode?

**Comment by charlottejruby** [comment]
Yes, I tried to change the mode of eval.py
![Screenshot from 2024-09-09 11-27-05](https://github.com/user-attachments/assets/18546723-d5e5-4b1f-9ed5-7e6c16c42745)

However, it doesn't work well.
Thanks for replying

**Comment by huangjy-pku** [comment]
The error you mentioned does not matter. I guess the visualization should work well if you set `headless=False`.

**Comment by charlottejruby** [comment]
![Screenshot from 2024-09-09 12-17-13](https://github.com/user-attachments/assets/daa0adc9-5e34-44e9-856e-bcca2bbcaaaf)
It doesn't work well.

I keep getting errors like the one shown below. I've been toggling the headless mode option , which was originally set to False, then I changed it to True, and back to False again.

I don't think this is a headless mode issue. Could you provide a different solution? I am running it in a Docker setup

![Screenshot from 2024-09-09 12-17-58](https://github.com/user-attachments/assets/5f3432f0-7369-423f-bdb3-c34a690602c1)

**Comment by rgong-bdai** [comment]
Hi, can you show the part the program crashed? like the end of the log.

**Comment by charlottejruby** [comment]
It seems that I encountered an error because I downloaded only part of the dataset.
Thank you for your help.
