### ISSUE TITLE
the problem of Omniverse

### ISSUE THREAD

**Issue by ljy1234-special** [arnold-benchmark/arnold#44]
Hi, the current omniverse only works with both versions 2023.2.1 and 4.1, what problems does the new version of omniverse cause? Or the nvidia website doesn't have 2022.1.1, so how can I download the previous version of omniverse?
![image](https://github.com/user-attachments/assets/8788ffe7-3eb2-4307-9316-365e21e9a161)

**Comment by ljy1234-special** [comment]
Hello, could you please reply in time?

**Comment by nikepupu** [comment]
Can you try docker setup?
