### ISSUE TITLE
How to run with two or more GPUS?

### ISSUE THREAD

**Issue by ChunkHsu** [arnold-benchmark/arnold#48]
When I'm training model, I encounter a CUDA out of memory error as follow:
![IMG_2200](https://github.com/user-attachments/assets/fd3835dc-dce1-4e9d-be18-da41395f27f9)
then I added another 3090 graphics,
![IMG_2199](https://github.com/user-attachments/assets/675ab39c-9f74-43ba-8b4c-afb8bbeaf863)
they can recongnized in the vagrant, but during runtime, only one GPU is being used instead of both.

**Comment by nikepupu** [comment]
We did not implement multi-GPU training; maybe you can use Accelerate? https://huggingface.co/docs/accelerate/en/index

**Comment by ChunkHsu** [comment]
ok，thanks
